### ISSUE TITLE
tab-picker无法使用

### ISSUE THREAD

**Issue by 291410392** [didi/mand-mobile-rn#36]
"react-native": "0.61.4",
"mand-mobile-rn": "0.1.0-beta.9",
tab-picker无法使用
---

注意：不是用 <a href="https://mand-mobile.github.io/mand-mobile-issue-helper/?project=mand-mobile-rn">Mand Mobile Issue Helper</a> 创建的 issue 会被立即关闭。

**Comment by 291410392** [comment]
五级数据到三级弹出就会退出，重新返回选择省的报错

**Comment by hbxeagle** [comment]
fixed in "mand-mobile-rn": "0.1.0-beta.10"

**Comment by 291410392** [comment]
@hbxeagle 目前的tabPicker的icon无法显示，MDTabs的样式也有问题，控制台提示，
Please update the following components: MDPopup, MDRadioList, MDTabBar, MDTabPicker, MDTabs，请问怎么解决

**Comment by hbxeagle** [comment]
@291410392 icon和样式问题，麻烦截个图。

**Comment by 291410392** [comment]
![66454419b706cb743373fcd10470cc4](https://user-images.githubusercontent.com/39253548/72027950-cb577100-32bb-11ea-895e-673f07d5754c.png)
![c9f74beabbf07435a8ebb74fc3c8a01](https://user-images.githubusercontent.com/39253548/72027951-cbf00780-32bb-11ea-9f09-2118e1f30085.png)

**Comment by IceBay** [comment]
@291410392 这个是字体文件没加载进来。试试 link
