### ISSUE TITLE
0.62版本提示ART被废除了,移到了社区维护了

### ISSUE THREAD

**Issue by 2788** [didi/mand-mobile-rn#47]
降级搞了一晚上 愣是没有运行起来这个项目....
有专门的react native mand 群吗

**Comment by xxyan0205** [comment]
点击链接加入群聊【Mand Mobile官方交流群】：https://jq.qq.com/?_wv=1027&k=5wlo2gM

**Comment by BarryZhan** [comment]
0.63 能支持吗

**Comment by ringlong** [comment]
我们正在支持0.63
